name = "CompactApproximation"
uuid = "e8e45b3e-8ddd-11e8-06ed-7b14989ec72f"
authors = ["vincentcp"]
version = "0.1.0"

[deps]
BasisFunctions = "8ac202e8-8a12-11e8-0422-2b902fe89c2d"
Domains = "a4a0b8aa-7ac0-11e8-2da9-8385f1ed8077"
FrameFun = "778aa48c-bd46-5276-944b-a086f2e2e18d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
